### ISSUE TITLE
Schema introspection request to public API is broken

### ISSUE THREAD

**Issue by jsstevenson** [dgidb/dgidb-v5#552]
This presumably has something to do with the logging updates introduced in the latest release. When issuing a request to the API:

```
   (1.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}", "graphql"=>{"query"=>"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}"}}
undefined method `flatten' for nil:NilClass

      results.flatten.tap { _1.select! { |r| r.is_a?(GraphQL::AnalysisError) } }
             ^^^^^^^^
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/analysis.rb:90:in `analysis_errors'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/analysis.rb:42:in `block (2 levels) in analyze_multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/analysis.rb:41:in `each'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/analysis.rb:41:in `each_with_index'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/analysis.rb:41:in `block in analyze_multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/tracing/trace.rb:32:in `analyze_multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/analysis.rb:25:in `analyze_multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/execution/interpreter.rb:47:in `block in run_all'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/tracing/trace.rb:40:in `execute_multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-batch-0.5.4/lib/graphql/batch/setup_multiplex.rb:24:in `execute_multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/execution/interpreter.rb:38:in `run_all'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/schema.rb:1375:in `multiplex'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/graphql-2.3.18/lib/graphql/schema.rb:1351:in `execute'
/Users/jss009/code/dgidb-v5/server/app/controllers/graphql_controller.rb:19:in `execute'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/abstract_controller/base.rb:228:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/notifications.rb:203:in `instrument'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-6.1.7.9/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/abstract_controller/base.rb:165:in `process'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal.rb:190:in `dispatch'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_controller/metal.rb:254:in `dispatch'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/routing/route_set.rb:842:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.10/lib/rack/etag.rb:27:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.10/lib/rack/conditional_get.rb:40:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.10/lib/rack/head.rb:12:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-6.1.7.9/lib/active_record/migration.rb:601:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.7.9/lib/rails/rack/logger.rb:37:in `call_app'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.7.9/lib/rails/rack/logger.rb:26:in `block in call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.7.9/lib/rails/rack/logger.rb:26:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.10/lib/rack/runtime.rb:22:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.9/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/static.rb:24:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.10/lib/rack/sendfile.rb:110:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.9/lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-mini-profiler-3.3.1/lib/mini_profiler.rb:334:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.7.9/lib/rails/engine.rb:539:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/configuration.rb:272:in `call'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/request.rb:100:in `block in handle_request'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/request.rb:99:in `handle_request'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/server.rb:464:in `process_client'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/server.rb:245:in `block in run'
/Users/jss009/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
Completed 500 Internal Server Error in 40ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 32297)
```

**Comment by jsstevenson** [comment]
Wait, I'm dumb. The problem is the client's schema

**Comment by jsstevenson** [comment]
You can still make schema-ignorant queries but the schema itself is inaccessible:

![Screenshot 2024-12-09 at 9 21 38 AM](https://github.com/user-attachments/assets/3f0d4c1f-4e83-48da-a167-31b43af8f4cc)
